// filepath: src/lib/ielts/listening1.ts
// IELTS Listening — 1-тест. 4 бөлім, 40 сұрақ.
// Нағыз формат: күнделікті диалог → монолог → талқылау → дәріс.

import type { ListeningTest } from "@/types/ielts";

export const listeningTest1: ListeningTest = {
  id: "listening-test-1",
  title: "Listening — Test 1",
  titleKk: "Тыңдау — 1-тест",
  type: "listening",
  totalQuestions: 40,
  sections: [
    // ═══════════ SECTION 1 (күнделікті диалог) ═══════════
    {
      id: "l1s1",
      number: 1,
      title: "Hotel Booking",
      titleKk: "Қонақүй брондау",
      context: "A conversation between a customer and a hotel receptionist about booking a room.",
      contextKk: "Қонақ пен қонақүй әкімшісі арасындағы бөлме брондау туралы әңгіме.",
      difficulty: "easy",
      audioLines: [
        { speaker: "Receptionist", text: "Good morning, Sunrise Hotel, how can I help you?", pauseAfter: 0.5 },
        { speaker: "Customer", text: "Hello, I'd like to book a room for next weekend, please.", pauseAfter: 0.5 },
        { speaker: "Receptionist", text: "Certainly. For how many nights would you like to stay?", pauseAfter: 0.5 },
        { speaker: "Customer", text: "Three nights, from Friday to Monday.", pauseAfter: 0.5 },
        { speaker: "Receptionist", text: "And how many people will be staying?", pauseAfter: 0.5 },
        { speaker: "Customer", text: "Two adults and one child.", pauseAfter: 0.5 },
        { speaker: "Receptionist", text: "We have a family room available at one hundred and twenty pounds per night. It includes breakfast.", pauseAfter: 0.5 },
        { speaker: "Customer", text: "That sounds good. Does the room have a sea view?", pauseAfter: 0.5 },
        { speaker: "Receptionist", text: "Yes, all our family rooms face the sea. Could I take your name, please?", pauseAfter: 0.5 },
        { speaker: "Customer", text: "It's Sarah Thompson. That's T-H-O-M-P-S-O-N.", pauseAfter: 0.5 },
        { speaker: "Receptionist", text: "Thank you. And a contact number?", pauseAfter: 0.5 },
        { speaker: "Customer", text: "Yes, it's oh-seven-seven-double-five, three-two-one, nine-eight-six.", pauseAfter: 0.5 },
        { speaker: "Receptionist", text: "Perfect. Your booking is confirmed. We look forward to seeing you on Friday.", pauseAfter: 0.5 },
      ],
      groups: [
        {
          id: "l1s1g1",
          type: "sentence-completion",
          instruction: "Complete the booking form. Write NO MORE THAN TWO WORDS OR A NUMBER for each answer.",
          instructionKk: "Брондау формасын толтырыңыз. Әр жауап үшін ЕКІ СӨЗ немесе САН жазыңыз.",
          wordLimit: 2,
          questions: [
            { id: "l1q1", type: "sentence-completion", number: 1, prompt: "Number of nights: _______", answer: "3", acceptableAnswers: ["three"], explanation: "Қонақ жұма мен дүйсенбі аралығы — 3 түн сұрады.", paragraphRef: 0 },
            { id: "l1q2", type: "sentence-completion", number: 2, prompt: "Number of adults: _______", answer: "2", acceptableAnswers: ["two"], explanation: "Екі ересек және бір бала.", paragraphRef: 0 },
            { id: "l1q3", type: "sentence-completion", number: 3, prompt: "Type of room: _______ room", answer: "family", explanation: "Отбасылық бөлме ұсынылды.", paragraphRef: 0 },
            { id: "l1q4", type: "sentence-completion", number: 4, prompt: "Price per night: _______ pounds", answer: "120", acceptableAnswers: ["one hundred and twenty"], explanation: "Түніне 120 фунт.", paragraphRef: 0 },
            { id: "l1q5", type: "sentence-completion", number: 5, prompt: "The room includes _______.", answer: "breakfast", explanation: "Таңғы ас кіреді.", paragraphRef: 0 },
            { id: "l1q6", type: "sentence-completion", number: 6, prompt: "Customer's surname: _______", answer: "Thompson", explanation: "Сара Томпсон.", paragraphRef: 0 },
          ],
        },
        {
          id: "l1s1g2",
          type: "true-false-notgiven",
          instruction: "Do the following statements agree with the conversation? Choose TRUE, FALSE or NOT GIVEN.",
          instructionKk: "Тұжырымдар әңгімемен сәйкес пе? TRUE, FALSE немесе NOT GIVEN.",
          questions: [
            { id: "l1q7", type: "true-false-notgiven", number: 7, prompt: "The family room has a sea view.", answer: "TRUE", explanation: "Барлық отбасылық бөлмелер теңізге қарайды.", paragraphRef: 0 },
            { id: "l1q8", type: "true-false-notgiven", number: 8, prompt: "The customer wants to pay in advance.", answer: "NOT GIVEN", explanation: "Алдын ала төлеу туралы айтылмаған.", paragraphRef: 0 },
            { id: "l1q9", type: "true-false-notgiven", number: 9, prompt: "The booking is for next weekend.", answer: "TRUE", explanation: "Келесі демалыс күндеріне.", paragraphRef: 0 },
            { id: "l1q10", type: "true-false-notgiven", number: 10, prompt: "The hotel is fully booked on Friday.", answer: "FALSE", explanation: "Бөлме бар, брондау расталды.", paragraphRef: 0 },
          ],
        },
      ],
    },
    // ═══════════ SECTION 2 (монолог — экскурсия) ═══════════
    {
      id: "l1s2",
      number: 2,
      title: "Museum Tour",
      titleKk: "Мұражай экскурсиясы",
      context: "A tour guide giving information about a museum to visitors.",
      contextKk: "Гид келушілерге мұражай туралы ақпарат беруде.",
      difficulty: "easy",
      audioLines: [
        { speaker: "Guide", text: "Welcome to the City History Museum. My name is David, and I'll be your guide today.", pauseAfter: 0.5 },
        { speaker: "Guide", text: "The museum was founded in nineteen sixty-five and is one of the oldest in the region.", pauseAfter: 0.5 },
        { speaker: "Guide", text: "We have four main galleries. The ground floor contains the ancient history collection.", pauseAfter: 0.5 },
        { speaker: "Guide", text: "On the first floor, you'll find the medieval gallery, which is our most popular exhibition.", pauseAfter: 0.5 },
        { speaker: "Guide", text: "The second floor houses the modern art collection, with paintings from the twentieth century.", pauseAfter: 0.5 },
        { speaker: "Guide", text: "The museum café is located on the ground floor, next to the main entrance, and is open until five o'clock.", pauseAfter: 0.5 },
        { speaker: "Guide", text: "Photography is allowed in most areas, but flash photography is not permitted in the medieval gallery.", pauseAfter: 0.5 },
        { speaker: "Guide", text: "Guided tours start every hour, and the last tour begins at four o'clock.", pauseAfter: 0.5 },
        { speaker: "Guide", text: "If you have any questions, our staff are wearing blue uniforms and are happy to help.", pauseAfter: 0.5 },
      ],
      groups: [
        {
          id: "l1s2g1",
          type: "sentence-completion",
          instruction: "Complete the notes. Write NO MORE THAN TWO WORDS OR A NUMBER for each answer.",
          instructionKk: "Жазбаларды толтырыңыз. ЕКІ СӨЗ немесе САН жазыңыз.",
          wordLimit: 2,
          questions: [
            { id: "l1q11", type: "sentence-completion", number: 11, prompt: "The museum was founded in _______.", answer: "1965", acceptableAnswers: ["nineteen sixty-five"], explanation: "1965 жылы құрылды.", paragraphRef: 0 },
            { id: "l1q12", type: "sentence-completion", number: 12, prompt: "The museum has _______ main galleries.", answer: "4", acceptableAnswers: ["four"], explanation: "Төрт негізгі галерея.", paragraphRef: 0 },
            { id: "l1q13", type: "sentence-completion", number: 13, prompt: "The ancient history collection is on the _______ floor.", answer: "ground", explanation: "Бірінші (ground) қабат.", paragraphRef: 0 },
            { id: "l1q14", type: "sentence-completion", number: 14, prompt: "The most popular exhibition is the _______ gallery.", answer: "medieval", explanation: "Орта ғасыр галереясы ең танымал.", paragraphRef: 0 },
            { id: "l1q15", type: "sentence-completion", number: 15, prompt: "The café is open until _______ o'clock.", answer: "5", acceptableAnswers: ["five"], explanation: "Бесте дейін.", paragraphRef: 0 },
          ],
        },
        {
          id: "l1s2g2",
          type: "multiple-choice",
          instruction: "Choose the correct letter, A, B, C or D.",
          instructionKk: "Дұрыс әріпті таңдаңыз: A, B, C немесе D.",
          questions: [
            { id: "l1q16", type: "multiple-choice", number: 16, prompt: "Where is the modern art collection?", options: ["Ground floor", "First floor", "Second floor", "Third floor"], answer: "2", explanation: "Екінші қабат — заманауи өнер (индекс 2).", paragraphRef: 0 },
            { id: "l1q17", type: "multiple-choice", number: 17, prompt: "Where is flash photography NOT allowed?", options: ["The café", "The medieval gallery", "The modern art collection", "The entrance"], answer: "1", explanation: "Орта ғасыр галереясында жарқылмен суретке тыйым (индекс 1).", paragraphRef: 0 },
            { id: "l1q18", type: "multiple-choice", number: 18, prompt: "When does the last guided tour begin?", options: ["Three o'clock", "Four o'clock", "Five o'clock", "Every hour"], answer: "1", explanation: "Соңғы тур сағат төртте (индекс 1).", paragraphRef: 0 },
            { id: "l1q19", type: "multiple-choice", number: 19, prompt: "How can visitors identify the staff?", options: ["They wear red uniforms", "They wear blue uniforms", "They carry badges", "They stand at the entrance"], answer: "1", explanation: "Қызметкерлер көк киім киеді (индекс 1).", paragraphRef: 0 },
            { id: "l1q20", type: "multiple-choice", number: 20, prompt: "Where is the café located?", options: ["First floor", "Second floor", "Ground floor near the entrance", "Outside the museum"], answer: "2", explanation: "Бірінші қабатта, кіреберіс жанында (индекс 2).", paragraphRef: 0 },
          ],
        },
      ],
    },
    // ═══════════ SECTION 3 (академиялық талқылау) ═══════════
    {
      id: "l1s3",
      number: 3,
      title: "Student Discussion",
      titleKk: "Студенттер талқылауы",
      context: "Two students discussing their research project with a tutor.",
      contextKk: "Екі студент оқытушымен зерттеу жобасын талқылауда.",
      difficulty: "medium",
      audioLines: [
        { speaker: "Tutor", text: "So, how is your research project on renewable energy progressing?", pauseAfter: 0.5 },
        { speaker: "Anna", text: "Quite well. We've finished collecting our data, but we're having trouble with the analysis.", pauseAfter: 0.5 },
        { speaker: "Tutor", text: "What kind of trouble?", pauseAfter: 0.5 },
        { speaker: "Ben", text: "We have a lot of survey responses, but we're not sure which statistical methods to use.", pauseAfter: 0.5 },
        { speaker: "Tutor", text: "How many responses did you receive in total?", pauseAfter: 0.5 },
        { speaker: "Anna", text: "We sent out four hundred surveys and received two hundred and fifty back.", pauseAfter: 0.5 },
        { speaker: "Tutor", text: "That's a good response rate. I'd suggest starting with descriptive statistics before anything more complex.", pauseAfter: 0.5 },
        { speaker: "Ben", text: "That makes sense. We were also wondering about the structure of our final report.", pauseAfter: 0.5 },
        { speaker: "Tutor", text: "The report should have five main sections: introduction, methodology, results, discussion, and conclusion.", pauseAfter: 0.5 },
        { speaker: "Anna", text: "And how long should it be?", pauseAfter: 0.5 },
        { speaker: "Tutor", text: "Around five thousand words, not including references. The deadline is the fifteenth of March.", pauseAfter: 0.5 },
        { speaker: "Ben", text: "Great. We should be able to finish by then.", pauseAfter: 0.5 },
      ],
      groups: [
        {
          id: "l1s3g1",
          type: "sentence-completion",
          instruction: "Complete the notes. Write NO MORE THAN TWO WORDS OR A NUMBER for each answer.",
          instructionKk: "Жазбаларды толтырыңыз. ЕКІ СӨЗ немесе САН жазыңыз.",
          wordLimit: 2,
          questions: [
            { id: "l1q21", type: "sentence-completion", number: 21, prompt: "The project is about _______ energy.", answer: "renewable", explanation: "Жаңартылатын энергия туралы.", paragraphRef: 0 },
            { id: "l1q22", type: "sentence-completion", number: 22, prompt: "Number of surveys sent out: _______", answer: "400", acceptableAnswers: ["four hundred"], explanation: "400 сауалнама жіберілді.", paragraphRef: 0 },
            { id: "l1q23", type: "sentence-completion", number: 23, prompt: "Number of responses received: _______", answer: "250", acceptableAnswers: ["two hundred and fifty"], explanation: "250 жауап алынды.", paragraphRef: 0 },
            { id: "l1q24", type: "sentence-completion", number: 24, prompt: "The report should be about _______ words.", answer: "5000", acceptableAnswers: ["five thousand"], explanation: "Шамамен 5000 сөз.", paragraphRef: 0 },
            { id: "l1q25", type: "sentence-completion", number: 25, prompt: "The deadline is the _______ of March.", answer: "15th", acceptableAnswers: ["fifteenth", "15"], explanation: "15 наурыз.", paragraphRef: 0 },
          ],
        },
        {
          id: "l1s3g2",
          type: "multiple-choice",
          instruction: "Choose the correct letter, A, B, C or D.",
          instructionKk: "Дұрыс әріпті таңдаңыз: A, B, C немесе D.",
          questions: [
            { id: "l1q26", type: "multiple-choice", number: 26, prompt: "What problem are the students having?", options: ["Collecting data", "Choosing statistical methods", "Finding participants", "Writing the introduction"], answer: "1", explanation: "Статистикалық әдістерді таңдау қиын (индекс 1).", paragraphRef: 0 },
            { id: "l1q27", type: "multiple-choice", number: 27, prompt: "What does the tutor suggest they start with?", options: ["Complex analysis", "Descriptive statistics", "Writing the conclusion", "More surveys"], answer: "1", explanation: "Сипаттамалық статистикадан бастау (индекс 1).", paragraphRef: 0 },
            { id: "l1q28", type: "multiple-choice", number: 28, prompt: "How many sections should the report have?", options: ["Three", "Four", "Five", "Six"], answer: "2", explanation: "Бес бөлім (индекс 2).", paragraphRef: 0 },
            { id: "l1q29", type: "multiple-choice", number: 29, prompt: "What is NOT one of the report sections mentioned?", options: ["Introduction", "Methodology", "Abstract", "Conclusion"], answer: "2", explanation: "Аннотация (abstract) аталмады (индекс 2).", paragraphRef: 0 },
            { id: "l1q30", type: "multiple-choice", number: 30, prompt: "What is the response rate considered to be?", options: ["Poor", "Average", "Good", "Excellent"], answer: "2", explanation: "Оқытушы жақсы жауап деңгейі деді (индекс 2).", paragraphRef: 0 },
          ],
        },
      ],
    },
    // ═══════════ SECTION 4 (дәріс) ═══════════
    {
      id: "l1s4",
      number: 4,
      title: "Lecture on Volcanoes",
      titleKk: "Жанартаулар туралы дәріс",
      context: "A university lecture about volcanoes.",
      contextKk: "Жанартаулар туралы университет дәрісі.",
      difficulty: "hard",
      audioLines: [
        { speaker: "Lecturer", text: "Today we're going to look at volcanoes, one of the most powerful natural phenomena on Earth.", pauseAfter: 0.5 },
        { speaker: "Lecturer", text: "A volcano is an opening in the Earth's surface through which molten rock, gases, and ash can escape.", pauseAfter: 0.5 },
        { speaker: "Lecturer", text: "There are around fifteen hundred active volcanoes in the world today.", pauseAfter: 0.5 },
        { speaker: "Lecturer", text: "Most volcanoes are located along the boundaries of tectonic plates, where the Earth's crust is weakest.", pauseAfter: 0.5 },
        { speaker: "Lecturer", text: "The largest concentration is found around the Pacific Ocean, in an area known as the Ring of Fire.", pauseAfter: 0.5 },
        { speaker: "Lecturer", text: "Volcanoes are generally classified into three types based on their shape and how they erupt.", pauseAfter: 0.5 },
        { speaker: "Lecturer", text: "Shield volcanoes are broad and flat, formed by runny lava that flows over great distances.", pauseAfter: 0.5 },
        { speaker: "Lecturer", text: "Composite volcanoes are tall and steep, and they produce the most violent eruptions.", pauseAfter: 0.5 },
        { speaker: "Lecturer", text: "Despite the dangers, around eight hundred million people live close to active volcanoes.", pauseAfter: 0.5 },
        { speaker: "Lecturer", text: "This is because volcanic soil is extremely fertile, making it ideal for agriculture.", pauseAfter: 0.5 },
      ],
      groups: [
        {
          id: "l1s4g1",
          type: "sentence-completion",
          instruction: "Complete the notes. Write NO MORE THAN TWO WORDS OR A NUMBER for each answer.",
          instructionKk: "Жазбаларды толтырыңыз. ЕКІ СӨЗ немесе САН жазыңыз.",
          wordLimit: 2,
          questions: [
            { id: "l1q31", type: "sentence-completion", number: 31, prompt: "There are about _______ active volcanoes in the world.", answer: "1500", acceptableAnswers: ["fifteen hundred", "1,500"], explanation: "Шамамен 1500 белсенді жанартау.", paragraphRef: 0 },
            { id: "l1q32", type: "sentence-completion", number: 32, prompt: "Most volcanoes are found at the boundaries of _______ plates.", answer: "tectonic", explanation: "Тектоникалық плиталар.", paragraphRef: 0 },
            { id: "l1q33", type: "sentence-completion", number: 33, prompt: "The area around the Pacific is called the Ring of _______.", answer: "Fire", explanation: "Отты сақина.", paragraphRef: 0 },
            { id: "l1q34", type: "sentence-completion", number: 34, prompt: "Volcanoes are classified into _______ types.", answer: "3", acceptableAnswers: ["three"], explanation: "Үш түрге бөлінеді.", paragraphRef: 0 },
            { id: "l1q35", type: "sentence-completion", number: 35, prompt: "_______ volcanoes are broad and flat.", answer: "Shield", explanation: "Қалқан жанартаулары жалпақ.", paragraphRef: 0 },
          ],
        },
        {
          id: "l1s4g2",
          type: "true-false-notgiven",
          instruction: "Do the following statements agree with the lecture? Choose TRUE, FALSE or NOT GIVEN.",
          instructionKk: "Тұжырымдар дәріспен сәйкес пе? TRUE, FALSE немесе NOT GIVEN.",
          questions: [
            { id: "l1q36", type: "true-false-notgiven", number: 36, prompt: "Composite volcanoes produce the most violent eruptions.", answer: "TRUE", explanation: "Композиттік жанартаулар ең қатты атқылайды.", paragraphRef: 0 },
            { id: "l1q37", type: "true-false-notgiven", number: 37, prompt: "Shield volcanoes are formed by thick, slow lava.", answer: "FALSE", explanation: "Қалқан жанартаулары сұйық лавадан түзіледі.", paragraphRef: 0 },
            { id: "l1q38", type: "true-false-notgiven", number: 38, prompt: "About 800 million people live near active volcanoes.", answer: "TRUE", explanation: "800 миллион адам жанартау маңында тұрады.", paragraphRef: 0 },
            { id: "l1q39", type: "true-false-notgiven", number: 39, prompt: "Volcanic soil is poor for farming.", answer: "FALSE", explanation: "Жанартау топырағы өте құнарлы.", paragraphRef: 0 },
            { id: "l1q40", type: "true-false-notgiven", number: 40, prompt: "The lecturer mentions a specific famous volcano by name.", answer: "NOT GIVEN", explanation: "Нақты жанартау аты аталмады.", paragraphRef: 0 },
          ],
        },
      ],
    },
  ],
};
