// filepath: src/lib/knowledge/methods.ts
// Тіл оқытудың атақты әдістемелері — толық, нақты.
// AI бұлардан жағдайға қарай таңдап қолданады.

import type { TeachingMethod } from "./types";

export const teachingMethods: TeachingMethod[] = [
  {
    id: "clt",
    name: "Communicative Language Teaching (CLT)",
    origin: "Dell Hymes, 1970s",
    principle: "Language is for communication. Fluency over perfect accuracy. Real, meaningful interaction.",
    whenToUse: "When the student needs to USE language in real situations, not just memorize rules.",
    howToApply: "Focus on getting the message across. Create real communicative situations. Don't interrupt every error — prioritize communication. Use role-plays, real tasks.",
    example: "Instead of 'conjugate the verb', ask 'Tell me about your weekend' — and respond as a real conversation partner.",
    bestFor: ["speaking", "writing"],
    levels: ["beginner", "intermediate", "advanced"],
  },
  {
    id: "tpr",
    name: "Total Physical Response (TPR)",
    origin: "James Asher, 1960s",
    principle: "Link language to physical action. The body helps memory. Lower anxiety.",
    whenToUse: "For beginners, action verbs, commands, and reducing the fear of speaking.",
    howToApply: "Connect words to actions and vivid mental images. For verbs, describe the physical motion. Make vocabulary 'physical' and memorable.",
    example: "Teaching 'jump' — describe the action vividly: 'Imagine your knees bending, then pushing up off the ground.'",
    bestFor: ["vocabulary", "listening"],
    levels: ["beginner"],
  },
  {
    id: "lexical",
    name: "The Lexical Approach",
    origin: "Michael Lewis, 1993",
    principle: "Language is grammaticalized lexis, not lexicalized grammar. Learn CHUNKS, not single words.",
    whenToUse: "Always — but especially for natural fluency and sounding native.",
    howToApply: "Teach collocations and fixed phrases ('make a decision', not 'make' + 'decision' separately). Point out word partnerships. Encourage learning phrases as units.",
    example: "Don't just teach 'strong'. Teach 'strong coffee', 'strong accent', 'a strong argument' — show what words go together.",
    bestFor: ["vocabulary", "speaking", "writing"],
    levels: ["intermediate", "advanced"],
  },
  {
    id: "tblt",
    name: "Task-Based Language Teaching (TBLT)",
    origin: "N. Prabhu, 1980s",
    principle: "Learn by completing real, meaningful TASKS. Language is a tool to achieve a goal.",
    whenToUse: "When the student wants practical, goal-oriented practice.",
    howToApply: "Give a task with a real outcome (plan a trip, solve a problem, make a decision together). Language emerges naturally from doing the task.",
    example: "'Let's plan a weekend trip to the mountains together. What should we pack?' — vocabulary and grammar arise from the task.",
    bestFor: ["speaking", "writing"],
    levels: ["intermediate", "advanced"],
  },
  {
    id: "ppp",
    name: "PPP (Presentation, Practice, Production)",
    origin: "Classic structured method",
    principle: "Present a structure → controlled practice → free production. Step by step.",
    whenToUse: "For teaching a specific new grammar point or structure clearly.",
    howToApply: "1) Present the rule with examples. 2) Guided practice (fill gaps, transform). 3) Free use in conversation. Move gradually from control to freedom.",
    example: "Present 'used to' → practice with prompts → ask 'What did you use to do as a child?'",
    bestFor: ["grammar"],
    levels: ["beginner", "intermediate"],
  },
  {
    id: "natural",
    name: "The Natural Approach",
    origin: "Krashen & Terrell, 1983",
    principle: "Acquisition over learning. Comprehensible input (i+1). Low affective filter (low stress).",
    whenToUse: "Always as a foundation. Especially when the student is anxious or stuck.",
    howToApply: "Give input slightly above their level but understandable. Keep stress LOW. Don't force production too early. Make it enjoyable and pressure-free.",
    example: "Use context, gestures, and simpler words to make a new structure understandable without translation.",
    bestFor: ["listening", "reading", "vocabulary"],
    levels: ["beginner", "intermediate"],
  },
  {
    id: "silent",
    name: "The Silent Way",
    origin: "Caleb Gattegno, 1963",
    principle: "The teacher stays silent; the student discovers. Self-correction builds independence.",
    whenToUse: "To build learner autonomy and pronunciation awareness.",
    howToApply: "Give minimal hints. Let the student figure out and self-correct. Ask guiding questions instead of giving answers directly.",
    example: "Instead of correcting directly, hint: 'Something about the verb tense here... can you find it?'",
    bestFor: ["grammar", "speaking"],
    levels: ["intermediate", "advanced"],
  },
  {
    id: "suggesto",
    name: "Suggestopedia",
    origin: "Georgi Lozanov, 1970s",
    principle: "Relaxation and positive suggestion accelerate learning. Remove mental barriers.",
    whenToUse: "When the student lacks confidence or believes they 'can't learn'.",
    howToApply: "Be extremely encouraging. Build confidence with positive suggestion. Create a relaxed, playful, low-pressure atmosphere.",
    example: "'You're picking this up really fast — your brain loves patterns. Let's play with this idea...'",
    bestFor: ["speaking", "vocabulary"],
    levels: ["beginner", "intermediate", "advanced"],
  },
  {
    id: "audiolingual",
    name: "Audio-Lingual Method (ALM)",
    origin: "1950s, behaviorism",
    principle: "Habit formation through repetition and drills. Pattern practice.",
    whenToUse: "For automating basic patterns and pronunciation until they're automatic.",
    howToApply: "Use substitution drills and repetition for core patterns. Build automaticity. (Use sparingly — combine with communication.)",
    example: "Pattern: 'I'm going to ___'. Substitute: study / sleep / eat — until it's automatic.",
    bestFor: ["grammar", "speaking"],
    levels: ["beginner"],
  },
  {
    id: "grammar-translation",
    name: "Grammar-Translation (used selectively)",
    origin: "Traditional",
    principle: "Explicit grammar rules and translation. Good for understanding, not fluency.",
    whenToUse: "Only to clarify a tricky rule via the student's native language (Kazakh).",
    howToApply: "Briefly explain a confusing rule by contrasting with Kazakh. Then immediately return to communicative practice. Don't overuse.",
    example: "Explain articles (a/the) by noting Kazakh has no articles — so they need extra attention.",
    bestFor: ["grammar"],
    levels: ["beginner", "intermediate"],
  },
];
